spring.application.name=springBoot_paymentsApp

# H2 Database (no installation needed)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

# Razorpay (keep same)
razorpay.key-id=rzp_test_SZmkSJNyKrpRjD
razorpay.key-secret=gMWjLENuVkIKHu5VUwE0d9AN